# Generated by Django 3.0.2 on 2020-01-21 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='example',
            old_name='word_id',
            new_name='word',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_id', to='dictionary.Category'),
            preserve_default=False,
        ),
    ]
