# Generated by Django 3.0.2 on 2020-02-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0012_auto_20200203_1456'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='example',
            constraint=models.UniqueConstraint(fields=('sentence', 'word'), name='uc_word_sentence'),
        ),
    ]
